---
- name: Setup NFS Server and Mount on Nodes
  hosts: masters
  become: true
  vars:
    nfs_export_dir: /mnt/nfs_share

  tasks:
    - name: Install NFS server package
      apt:
        name:
          - nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create NFS export directory
      file:
        path: "{{ nfs_export_dir }}"
        state: directory
        mode: '0777'

    - name: Configure NFS exports for each worker
      blockinfile:
        path: /etc/exports
        block: |
          {% for host in groups['workers'] %}
          {{ nfs_export_dir }} {{ hostvars[host]['ansible_host'] }}(rw,sync,no_subtree_check,no_root_squash)
          {% endfor %}
        state: present

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted

- name: Setup NFS Server and Mount on Nodes
  hosts: workers
  become: true
  vars:
    nfs_mount_point: /mnt/nfs_share
  tasks:

    - name: Install nfs client package
      apt:
        name:
          - nfs-common
        state: present

    - name: Ensure NFS mount point exists
      file:
        path: "{{ nfs_mount_point }}"
        state: directory
        mode: '0777'

    - name: Mount NFS share
      mount:
        path: "{{ nfs_mount_point }}"
        src: "{{ hostvars['master']['ansible_host'] }}:{{ nfs_mount_point }}"
        fstype: nfs
        opts: rw
        state: mounted

