- name: Configure Join Commands on Master Node
  hosts: master
  become: yes
  tasks:
    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- name: Join Worker Nodes to Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Retrieve Join Command from Master
      set_fact:
        join_command: "{{ hostvars['master'].join_command }}"
      
    - name: Run Join Command on Worker
      shell: "{{ join_command }}"
