apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ip-lookup.fullname" . }}
  labels:
    {{- include "ip-lookup.labels" . | nindent 4 }}
{{- with .Values.configmap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
