{{- if .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ip-lookup-migrations-pvc
  labels:
    {{- include "ip-lookup.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
