apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ip-lookup.fullname" . }}
  labels:
    {{- include "ip-lookup.labels" . | nindent 4 }}
{{- with .Values.secret }}
type: Opaque
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
