name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: registry-ce4439d8b9-ip-lookup.apps.ir-central1.arvancaas.ir
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Version from Tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker build -t registry-ce4439d8b9-ip-lookup.apps.ir-central1.arvancaas.ir/ip-lookup:${{ env.VERSION }} ip-lookup/
        docker push registry-ce4439d8b9-ip-lookup.apps.ir-central1.arvancaas.ir/ip-lookup:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl get nodes
        helm list

    - name: Deploy with Helm
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_PASS: ${{ secrets.DB_PASS }}
      run: |
        helm upgrade --install ip-lookup ./helm-chart \
          --set secret.DATABASE_URL=$DATABASE_URL \
          --set secret.DB_PASS=$DB_PASS \
          --set image.repository=registry-ce4439d8b9-ip-lookup.apps.ir-central1.arvancaas.ir/ip-lookup \
          --set image.tag=${{ env.VERSION }}
